/**
 * 
 */
package fr.wati.scool.web;

import static org.springframework.beans.factory.config.BeanDefinition.SCOPE_PROTOTYPE;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.HorizontalLayout;

/**
 * @author Rachid Ouattara
 * 
 */

@Component
@Scope(SCOPE_PROTOTYPE)
@SuppressWarnings("serial")
public class MainStatusBar extends HorizontalLayout {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public MainStatusBar() {
		addStyleName("status-bar");
		// buildMainLayout();
		// setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new AbsoluteLayout();
	}

}
