/**
 * 
 */
package fr.wati.scool.web.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.VerticalLayout;

import fr.wati.scool.web.MainStatusBar;
import fr.wati.scool.web.components.HeaderHorizontalBar;
import fr.wati.scool.web.components.TopHorizontalMenuBar;

/**
 * @author Rachid Ouattara
 * 
 */

@SuppressWarnings("serial")
public class MainView extends CustomComponent implements View {

	public static final String NAME = "";

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private CssLayout mainLayout;
	@AutoGenerated
	private VerticalLayout globalVerticalLayout;
	@AutoGenerated
	private VerticalLayout middleVerticalLayout;
	@AutoGenerated
	private VerticalLayout menuBarVerticalLayout;
	private CssLayout content = new CssLayout();
	private MainStatusBar mainStatusBar = new MainStatusBar();

	private Navigator navigator;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 * 
	 * @param navigator
	 */
	public MainView() {
	}

	@AutoGenerated
	private CssLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new CssLayout();
		mainLayout.setImmediate(false);
		// mainLayout.addStyleName("root");
		mainLayout.setSizeFull();
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		// globalHorizontalLayout
		globalVerticalLayout = buildGlobalHorizontalLayout();
		mainLayout.addComponent(globalVerticalLayout);

		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildGlobalHorizontalLayout() {
		// common part: create layout
		globalVerticalLayout = new VerticalLayout();
		globalVerticalLayout.addStyleName("main-view");

		// Header
		HeaderHorizontalBar headerHorizontalBar = new HeaderHorizontalBar();
		headerHorizontalBar.build();
		globalVerticalLayout.addComponent(headerHorizontalBar);
		// globalVerticalLayout.setExpandRatio(headerHorizontalBar, 0.5f);
		// Top horizontal bar
		TopHorizontalMenuBar topHorizontalMenuBar = new TopHorizontalMenuBar();
		topHorizontalMenuBar.build();
		globalVerticalLayout.addComponent(topHorizontalMenuBar);
		// globalVerticalLayout.setExpandRatio(topHorizontalMenuBar, 0.5f);
		// Content
		content.addStyleName("view-main-content");
		globalVerticalLayout.addComponent(content);
		// globalVerticalLayout.setExpandRatio(content, 7.5f);
		// Status bar
		globalVerticalLayout.addComponent(mainStatusBar);
		// globalVerticalLayout.setExpandRatio(mainStatusBar, 0.5f);

		return globalVerticalLayout;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.vaadin.navigator.View#enter(com.vaadin.navigator.ViewChangeListener
	 * .ViewChangeEvent)
	 */
	@Override
	public void enter(ViewChangeEvent event) {
		System.out.println("Should handle from main view:"
				+ event.getParameters());
		content.removeAllComponents();
		MenuBar menuBar = null;
		if (event != null && event.getOldView() != null
				&& event.getOldView() instanceof HasMenuBar) {
			menuBar = ((HasMenuBar) event.getOldView()).getMenuBar();
		}
//		switch (event.getParameters()) {
//		case DashBoardView.NAME:
//			content.addComponent(new DashBoardView(navigator));
//			break;
//		case AdminView.NAME:
//			content.addComponent(new AdminView(navigator));
//			break;
//		case TimeTableView.NAME:
//			content.addComponent(new TimeTableView(navigator));
//			break;
//		case UsersEditionView.NAME:
//			content.addComponent(new UsersEditionView(navigator));
//			break;
//		case UsersRightsManagementView.NAME:
//			content.addComponent(new UsersRightsManagementView(navigator));
//			break;
//		case ConfigurationView.NAME:
//			content.addComponent(new ConfigurationView(navigator));
//			break;
//		case LogView.NAME:
//			content.addComponent(new LogView(navigator));
//			break;
//		default:
//			break;
//		}

	}

}
